project_id = "muejwgnmxqvcwuadubpz"

[api]
enabled = true
schemas = ["public", "graphql_public", "spondon"]
extra_search_path = ["public", "extensions", "spondon"]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://*.vercel.app/**"]
